create table if not exists public.snoozed_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  alert_id text not null,
  snoozed_until timestamptz,
  is_deferred boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, alert_id)
);

alter table public.snoozed_alerts enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'snoozed_alerts'
      and policyname = 'snoozed_alerts_own'
  ) then
    create policy "snoozed_alerts_own" on public.snoozed_alerts
      for all
      using (user_id = auth.uid())
      with check (user_id = auth.uid());
  end if;
end $$;

create index if not exists idx_snoozed_alerts_user on public.snoozed_alerts (user_id);
